version: "3.1"

services:
  server:
    image: vagranttiger/php7-nginx
    restart: always
    container_name: pacmsAdmin
    volumes:
      - ./:/var/www/app
    depends_on:
      - db
      - redis
    ports:
      - 8080:80
  db:
    image: mysql:5.7
    restart: always
    container_name: pacmsDB
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - C:\Users\12034\conf\mysql\conf\mysql:/etc/mysql
      - C:\Users\12034\conf\mysql\lib:/var/lib/mysql
  redis:
    image: redis:latest
    restart: always
    container_name: pacmsRedis
    ports:
      - 6379:6379
    command:
      redis-server
    volumes:
      - C:\Users\12034\conf\redis\data:/data